#!/usr/bin/env python3
# title: test_examples.py
# project: ProSIFT
# author: Reina Hastings
# contact: reinahastings13@gmail.com
# date created: 2026-10-01
# last modified: 2026-10-01
#
# purpose:
#   Regression guard for the shipped example (assets/examples/minimal). The
#   committed files are generated by assets/examples/generate_examples.py and
#   must not drift from it: regenerating with the default seed must reproduce
#   every committed text file byte-for-byte. The .xlsx template is excluded
#   (its zip/XML serialization varies with the openpyxl version).
#
# inputs:
#   - assets/examples/generate_examples.py (run in a subprocess)
#   - assets/examples/minimal/* (committed example files)
#
# outputs:
#   - Test results (stdout via pytest); generator output goes to tmp_path.
#
# usage example:
#   "$(conda info --base)/envs/prosift/bin/python" -m pytest tests/test_examples.py -q
#
#   copy/paste: "$(conda info --base)/envs/prosift/bin/python" -m pytest tests/test_examples.py -q

import subprocess
import sys
from pathlib import Path

import pytest

EXAMPLES = Path(__file__).resolve().parent.parent / 'assets' / 'examples'
COMMITTED = EXAMPLES / 'minimal'
TEXT_FILES = [
    'params.yml', 'abundance.csv', 'metadata.csv', 'samplesheet.csv',
    'ground_truth.csv', 'example_gene_sets.gmt',
]
XLSX = 'ProSIFT_input_template.xlsx'


@pytest.fixture(scope='module')
def regenerated(tmp_path_factory) -> Path:
    outdir = tmp_path_factory.mktemp('regen')
    subprocess.run(
        [sys.executable, str(EXAMPLES / 'generate_examples.py'),
         '--outdir', str(outdir), '--no-xlsx'],
        check=True, capture_output=True,
    )
    return outdir


def test_file_sets_match(regenerated):
    # Guards TEXT_FILES itself: a new generator output, or a stray file
    # committed under minimal/, must show up here instead of going unchecked.
    committed = {p.name for p in COMMITTED.iterdir() if not p.name.startswith('.')}
    produced = {p.name for p in regenerated.iterdir()}
    assert committed == set(TEXT_FILES) | {XLSX}
    assert produced == set(TEXT_FILES)   # --no-xlsx run


@pytest.mark.parametrize('name', TEXT_FILES)
def test_regeneration_reproduces_committed_file(regenerated, name):
    produced = (regenerated / name).read_bytes()
    committed = (COMMITTED / name).read_bytes()
    assert produced == committed, (
        f'{name} differs from its generator output; edit generate_examples.py '
        f'and regenerate instead of hand-editing assets/examples/minimal/{name}')
